version: '4.30.0'
services:
  my-sql:
    image: mysql:latest
    container_name: my-sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nestjs-test
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./data/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - my-sql
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: my-sql
      PMA_USER: root
      PMA_PASSWORD: 'root'
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    volumes:
      - ./data/phpmyadmin
